image: golang:1.22

stages:
  - test
  - build
  - release

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: 0

test:
  stage: test
  script:
    - go test -v ./...
  except:
    - tags

build:
  stage: build
  script:
    - go build -o semrel-gitlab
  artifacts:
    paths:
      - semrel-gitlab
  except:
    - tags

release:
  stage: release
  image: ghcr.io/fanny7d/semrel-gitlab:latest
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "main" || "$CI_COMMIT_BRANCH" == "master" ]]; then
        # 检查是否有需要发布的变更
        if ./semrel-gitlab next-version --allow-current > .next-version; then
          VERSION=$(cat .next-version)
          # 创建标签和发布
          ./semrel-gitlab tag --ci-commit-tag v$VERSION
          # 生成变更日志
          ./semrel-gitlab changelog
          # 提交变更日志
          git add CHANGELOG.md
          git commit -m "docs: 更新变更日志 [skip ci]"
          git push origin HEAD:$CI_COMMIT_BRANCH
        fi
      fi
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master"'
      when: on_success
    - when: never
